# -*- coding: utf-8 -*-
"""yolo_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dy9DKoTtCALwRsE9XYP-DRpU0hMjuU3W
"""

import os
os.chdir('/content/drive/MyDrive/Yolo_training')

ls

!git clone https://github.com/ultralytics/yolov5.git

os.chdir('yolov5')

ls

!pip install -r requirements.txt

!python train.py --data data_yaml.txt --cfg yolov5s.yaml --batch-size 8 --name Model --epochs 100 --single-cls

!python export.py --weights runs/train/Model2/weights/best.pt --include onnx --simplify --opset 12

